blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, validators, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField('Title',[validators.DataRequired()])
    text = TextAreaField('Text', [validators.DataRequired()])
    tags = SelectMultipleField("Tags", coerce=int)
    submit = SubmitField('Create')

blog/article/views.py
from sqlite3 import IntegrityError

import requests as requests
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.config import API_URL
from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

articles_app = Blueprint("articles_app", __name__, url_prefix='/articles', static_folder='../static')

# ARTICLES = {
#     1: {
#         'title': 'title_1',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Aleks',
#             'id': 1,
#         },
#     },
#     2: {
#         'title': 'title_2',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Jon',
#             'id': 2,
#         },
#     },
#     3: {
#         'title': 'title_3',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Ivan',
#             'id': 3,
#         },
#     },
#     4: {
#         'title': 'title_4',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Aleks',
#             'id': 1,
#         },
#     },
#     5: {
#         'title': 'title_5',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Jon',
#             'id': 2,
#         },
#     },
#     6: {
#         'title': 'title_6',
#         'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus laoreet dapibus ipsum, '
#                 'fringilla pharetra ante condimentum sed. Mauris quis mi eu est rhoncus ornare vitae vel lacus. '
#                 'Praesent id scelerisque neque. Quisque sed augue vitae urna finibus volutpat eget nec nisl. '
#                 'Proin nisi mauris, faucibus eget eros convallis, congue tempus mi. Integer facilisis feugiat lacus, '
#                 'sit amet porta sapien tempus ac. Fusce tincidunt rhoncus ipsum, at tempor urna viverra varius. '
#                 'Duis a erat dictum, molestie erat eget, pellentesque nisl. Mauris fringilla in urna ac luctus. '
#                 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mi purus, tincidunt '
#                 'non condimentum eu, aliquam nec augue. Suspendisse finibus purus quis leo tincidunt, eget tincidunt '
#                 'metus consequat. In congue sodales condimentum.',
#         'author': {
#             'name': 'Ivan',
#             'id': 3,
#         },
#     }
# }
#

@articles_app.route("/", methods=["GET"])
@login_required
def articles_list():
    articles: Article = Article.query.all()
    # call RPC method
    count_articles = requests.get(f'{API_URL}/api/articles/event_get_count/').json
    return render_template("articles/list.html", articles=articles, count_articles=count_articles['count'])


@articles_app.route("/create", methods=["GET"])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    return render_template("articles/create.html", form=form)



@articles_app.route("/create", methods=["POST"])
@login_required
def create_article():
    errors = []
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)
        # db.session.add(_article)

        if request.method == "POST" and form.validate_on_submit():
            if form.tags.data:
                selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
                for tag in selected_tags:
                    _article.tags.append(tag)


        if not current_user.author:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.commit()

        _article.author_id = current_user.author.id

        db.session.add(_article)
        db.session.commit()
        return redirect(url_for("articles_app.details", article_id=_article.id))


    return render_template('articles/create.html', form=form)


@articles_app.route('/<int:article_id>')
@login_required
def details(article_id: int):

    _article = Article.query.filter_by(id=article_id).options(joinedload(Article.tags)).one_or_none()


    if _article is None:
        raise NotFound(f"Article #{article_id} doesn't exist!")

    return render_template('articles/details.html', article=_article)

# @articles_app.route('/<int:pk>')
# def get_article(pk: int):
#     try:
#         article = ARTICLES[pk]
#     except KeyError:
#         raise NotFound(f'Article id {pk} not found')
#     return render_template('articles/details.html', article=article)

blog/templates/articles/create.html
{% extends 'base.html' %}
{% from 'macro/formhelpers.html' import render_field %}

{% block title %}
    Create article
{% endblock %}

{% block body %}
    <h1>Create article</h1>
    {% if errors %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST">
        {{ form.csrf_token }}
        {% for field in ['title', 'text', 'tags'] %}
            {{ render_field(form[field]) }}
        {% endfor %}

       <div>
            {{ form.submit(class="btn btn-primary mb-3") }}
        </div>
    </form>

{% endblock %}

blog/templates/articles/details.html
{% extends 'base.html' %}
{% block title %}
    {{ article.title }}
{% endblock %}
{% block body %}
     {% if current_user.is_authenticated %}
        <div>
            <a href="{{ url_for('articles_app.articles_list') }}">Back to articles list</a>
        </div>
        <h2>{{ article.title }}</h2>
<!--        <h3>{{ article.author.name }}</h3>-->
        <br><br>
        <div class="row">
            <div class="col-md-12">{{ article.text }}</div>
        </div>
        <div class="row">
            <div class="col-6">
                <div><small class="text-muted">Author: {{ article.author.user.first_name }} {{ article.author.user.last_name }} ({{ article.author.id }})</small></div>
                <div><small class="text-muted">Created at: {{ article.created_at.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
                <div><small class="text-muted">Updated at: {{ article.updated_at.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
            </div>
            <div class="col-6">
                {% if article.tags %}
                    <div>Tags:</div>
                    {% for tag in article.tags %}
                        <span class="badge bg-primary">{{ tag.name }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>


    {% else %}
        <h2>You can`t see it. Login</h2>
        <a href="{{ url_for('auth_app.login') }}">Login</a>
    {% endif %}
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}
  Articles list
{% endblock %}
{% block body %}
  <h2>Articles (count: {{ count_articles }}, obtained from RPC call):</h2>
  <div>
      <table>
          <tbody>
              <tr>
                  <th>Number</th><th>Title</th><th>Author</th>
              </tr>
              {% for article in articles %}
                <tr>
                    <td>{{ article.id }}</td>
                    <td><a href="{{ url_for('articles_app.details', article_id=article.id) }}">{{ article.title }}</a></td>
                    <td><a href="{{ url_for('users_app.profile', pk=article.author.id) }}">{{ article.author.user.last_name }}</a></td>
                </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
{% endblock %}