blog/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField


class UserRegisterForm(FlaskForm):
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    username = StringField("Username", [validators.DataRequired()])
    email = StringField("Email Address",
        [
            validators.DataRequired(),
            validators.Email(),
            validators.Length(min=6, max=200)
        ],
        filters=[lambda data: data and data.lower()])
    password = PasswordField("Password", [validators.DataRequired(),
                                          validators.EqualTo("confirm_password", message="Field must be equal to password")])
    confirm_password = PasswordField("Confirm Password", [validators.DataRequired()])
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email = StringField("Email Address",
                        [
                            validators.DataRequired(),
                            validators.Email(),
                            validators.Length(min=6, max=200)
                        ],
                        filters=[lambda data: data and data.lower()])
    password = PasswordField("Password", [validators.DataRequired()],)
    submit = SubmitField("Login")

blog/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request, current_app
from flask_login import login_required, current_user, login_user
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models import User

users_app = Blueprint('users_app', __name__, url_prefix='/users', static_folder='../static')

# USERS = ['Aleks', 'Jon', 'Ivan']
# USERS = {
#     1: 'Aleks',
#     2: 'Jon',
#     3: 'Ivan'
# }


@users_app.route('register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users_app.profile', pk=current_user.id))

    errors = None
    form = UserRegisterForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email not uniq")
            return render_template("users/register.html", form=form)

    _user = User(
        first_name=form.first_name.data,
        last_name=form.last_name.data,
        username=form.username.data,
        email=form.email.data,
        password=generate_password_hash(form.password.data),
    )

    db.session.add(_user)
    try:
        db.session.commit()
    except IntegrityError:
        current_app.logger.exception("Could not create user!")
        error = "Could not create user!"
    else:
        current_app.logger.info("Created user %s", _user)
        login_user(_user)
        return redirect(url_for("users_app.profile", pk=current_user.id))

    return render_template('users/register.html', form=form, errors=errors)

@users_app.route('/')
def users_list():
    # from blog.models import User
    users = User.query.all()
    return render_template('users/list.html', users=users)

@users_app.route('/<int:pk>')
@login_required
def profile(pk: int):
    # try:
    #     user_name = USERS[pk]
    # except KeyError:
    #     raise NotFound(f'User id {pk} not found')
    # from blog.models import User
    user = User.query.filter_by(id=pk).one_or_none()
    if user is None:
        raise NotFound(f"User #{pk} doesn't exist!")

    return render_template('users/details.html', user=user)

blog/templates/users/details.html
{% extends 'base.html' %}
{% block title %}
    User detail
{% endblock %}
{% block body %}
     {% if current_user.is_authenticated %}
        <div>
            <a href="{{ url_for('users_app.users_list') }}">Back to users list</a>
        </div>
        <h1>{{ user.username }}</h1>
    {% else %}
        <h2>You can`t see it. Login</h2>
        <a href="{{ url_for('auth_app.login') }}">Login</a>
    {% endif %}
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html' %}
{% block title %}
    User list
{% endblock %}
{% block body %}
    <h1>Users:</h1>
    {% for user in users %}
        <div class="row">
            <div class="col">
                <ul>
                    <li><a href="{{ url_for('users_app.profile', pk=user.id) }}">
                        {{ user.username }}
                        </a>
                        {% if user.is_staff %}
                            <span class="badge bg-secondary">staff</span>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

    {% endfor %}
{% endblock %}

blog/templates/users/register.html
{% extends 'base.html' %}
{% from 'macro/formhelpers.html' import render_field %}


{% block title %}
    User register
{% endblock %}

{% block body %}
    {% if errors %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="POST">
        {{ form.csrf_token }}

        {% for field in ['first_name', 'last_name', 'username', 'email', 'password', 'confirm_password'] %}
            {{ render_field(form[field]) }}
        {% endfor %}

        <div>
            {{ form.submit(class="btn btn-primary mb-3") }}
        </div>
    </form>


{% endblock %}